version: 0.0
os: linux
hooks:
  BeforeInstall:    
    - location: Install.sh
      timeout: 300
      runas: root
 
 # AfterInstall:
 #   - location: Install.sh Backupcode.sh
 #     timeout: 30
 #     runas: root
      
